# Global Settings
server.port=8081
spring.profiles.active=mysql


# POSTGRES (Aiven)
# This block is only read if spring.profiles.active=postgres
#spring.config.activate.on-profile=postgres
#spring.datasource.url=jdbc:postgresql://ofs-db-26-ofs-banking-2026.j.aivencloud.com:13225/defaultdb?ssl=require
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_TLW_-5U5P_U6T-qeqHs
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update


# MYSQL (Local)
spring.config.activate.on-profile=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/ofs_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=IamIronman
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# =========================================================
# COMMON CONFIGURATIONS (Always Active)
# =========================================================
# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://it24ganeshprabhu_db_user:5X3K3nFp9osMV2xe@adhaar-demo.zmfs8mq.mongodb.net/Adhaar-demo?retryWrites=true&w=majority

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=online.financial.services.000@gmail.com
spring.mail.password=gije risd pjsa xnhw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

# AI API Key
groq.api.key=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