# Global Settings

server.port=${PORT}
spring.profiles.active=mysql

# POSTGRES (Aiven)
# This block is only read if spring.profiles.active=postgres
#spring.config.activate.on-profile=postgres
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

# MYSQL (Local / Railway)
spring.config.activate.on-profile=mysql

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# =========================================================
# COMMON CONFIGURATIONS (Always Active)
# =========================================================

# MongoDB Atlas Configuration
spring.data.mongodb.uri=${MONGO_URI}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=online.financial.services.000@gmail.com
# Use GMAIL_APP_PASS in Railway Variables
spring.mail.password=${GMAIL_APP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

# AI API Key
groq.api.key=${GROQ_API_KEY}
